#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Uso: alias-remove <nome-do-alias> <arquivo>"
    exit 1
fi

alias_name="$1"
alias_file="$2"
file_path="$HOME/aliases/src/${alias_file}.alias"

if [ ! -f "$file_path" ]; then
    echo "O arquivo '$alias_file.alias' não existe."
    exit 1
fi

temp_file=$(mktemp)
found=0
prev_line=""
skip_next=0

while IFS= read -r line || [ -n "$line" ]; do
    if [ $skip_next -eq 1 ]; then
        skip_next=0
        continue
    fi
    
    if [[ $line == "# Alias adicionado em"* ]]; then
        read -r next_line
        if [[ $next_line == "alias $alias_name="* ]]; then
            found=1
            skip_next=1
            continue
        else
            echo "$line" >> "$temp_file"
            echo "$next_line" >> "$temp_file"
        fi
    else
        echo "$line" >> "$temp_file"
    fi
    prev_line="$line"
done < "$file_path"

if [ $found -eq 1 ]; then
    mv "$temp_file" "$file_path"
    echo "Alias '$alias_name' removido do arquivo '$alias_file.alias'."
    source "$file_path"
    echo "Aliases recarregados."
else
    rm "$temp_file"
    echo "Alias '$alias_name' não encontrado."
fi