name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr/local

    - name: Run ShellCheck
      run: |
        shellcheck bin/* lib/*.sh share/*.sh setup.sh uninstall.sh

    - name: Run Sets
      run: bats tests/
